Steven pictures
googleinterns/step92-2020 pull request #80
Opened 2020-08-05 18:33 UTC by smarquez-jpg

2020-08-05 22:24 UTC, Andrewmob2703-zz reviewed
Cool, I'll see if I can use fetch to post it

2020-08-06 06:14 UTC, peizhaoou approved these changes
I think it's definitely to put a more descriptive description for the PR:) I haven't been able to look very deep into all the details, but given the time constraint, please ensure this is manually tested  before merge.

2020-08-06 06:26 UTC, Andrewmob2703-zz requested changes
Requesting changes to prevent accidental merge. Still working on getting fetch to post images.

2020-08-07 21:18 UTC, Andrewmob2703-zz approved these changes

2020-08-07 21:19 UTC, closed without merging