Added test for doGetFromDatastore
googleinterns/step92-2020 pull request #81
Opened 2020-08-05 19:37 UTC by smarquez-jpg

2020-08-05 20:31 UTC, martiKallas requested changes
Thanks for starting this, Steven! Feel free to get help from your podmates too.

2020-08-05 20:31 UTC, martiKallas commented on portfolio/src/test/java/com/google/sps/DatastoreUtilsTest.java
> +    Assert.assertEquals(1, actual.size());
You need some extra checks here. You want this to fail if doGetFromDatastore changes in an unwanted way. doGetFromDatastore has 3 functions that it calls: putRepliesWithPosts, updateTagsToSearch, and sortAndLoadfromBlogHashmap. You will need to check the output from doGetFromDatastore to confirm that each of these are called.

2020-08-06 02:18 UTC, Andrewmob2703-zz reviewed
I probably should have tested this since I added new functionality.
New Tests Added.

2020-08-06 05:53 UTC, martiKallas approved these changes
Nice changes!

I still don't think this tests if replies get attached to posts, but feel free to submit in the interest of time.

2020-08-06 06:32 UTC, Andrewmob2703 commented
> Nice changes!
> 
> I still don't think this tests if replies get attached to posts, but feel free to submit in the interest of time.

I think Steven tested that already in lines 100-112.

2020-08-06 14:42 UTC, merged